config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  use_doorkeeper
  devise_for :users
  resources :entries
  draw :api
   # global options responder -> makes sure OPTION request for CORS endpoints work
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
    
end

app/controllers/api/v1/andriod/entries_controller.rb
class Api::V1::Android::EntriesController < ApplicationController
    include ApplicationHelper
    before_action :set_entry, only: %i[ show ]
    skip_before_action :doorkeeper_authorize!
    before_action :is_admin?
    
    # GET /entries or /entries.json
    def index
      @entries = Entry.all
      respond_to do |format|
        format.json { render json: @entries }
      end
    end
  
    # GET /entries/1 or /entries/1.json
    def show
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_entry
        @entry = Entry.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def entry_params
        params.require(:entry).permit(:upload, :download)
      end
  end
  

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController < ApiController
    before_action :set_entry, only: %i[ show edit update destroy ]
    skip_before_action :doorkeeper_authorize!, only: %i[create index show new edit update destroy]
       
    include DoorkeeperRegisterable
    # GET /entries or /entries.json
    def index
      @entries = Entry.all
      respond_to do |format|
        format.json { render json: @entries }
        format.html { redirect_to root_url }
      end
    end
  
    # GET /entries/1 or /entries/1.json
    def show
    end
  
    # GET /entries/new
    def new
      @entry = Entry.new
    end
  
    # GET /entries/1/edit
    def edit
    end
  
    # POST /entries or /entries.json
    def create      
      @entry = Entry.new(entry_params)      
        if @entry.save
          render json: { status: :ok}
          # format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
          # format.json { render :show, status: :created, location: @entry }
        else
          # format.html { render :new, status: :unprocessable_entity }
          # format.json { render json: @entry.errors, status: :unprocessable_entity }
          render json:  {status: :unprocessable_entity}        
      end
    end
  
    # PATCH/PUT /entries/1 or /entries/1.json
    def update
      respond_to do |format|
        if @entry.update(entry_params)
          format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
          format.json { render :show, status: :ok, location: @entry }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /entries/1 or /entries/1.json
    def destroy
      @entry.destroy
  
      respond_to do |format|
        format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_entry
        @entry = Entry.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def entry_params
        params.permit(:upload, :download, :lat, :lng)
      end
  end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:upload, :download)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :upload %>
    <%= form.number_field :upload %>
  </div>

  <div class="field">
    <%= form.label :download %>
    <%= form.number_field :download %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Upload</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.upload %></td>
        <td><%= entry.download %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Upload:</strong>
  <%= @entry.upload %>
</p>

<p>
  <strong>Download:</strong>
  <%= @entry.download %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>